//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVT_Said_Riedl
{
    using System;
    using System.Collections.Generic;
    
    public partial class meetings
    {
        public int mee_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> room_time_id { get; set; }
        public Nullable<int> therapist_treatment_id { get; set; }
    
        public virtual patients patients { get; set; }
        public virtual room_times room_times { get; set; }
        public virtual therapist_treatments therapist_treatments { get; set; }
    }
}
