//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVT_Said_Riedl
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_times
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public room_times()
        {
            this.meetings = new HashSet<meetings>();
        }
    
        public int rti_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> time_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<meetings> meetings { get; set; }
        public virtual rooms rooms { get; set; }
        public virtual times times { get; set; }
    }
}
