//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVT_Said_Riedl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<addresses> addresses { get; set; }
        public virtual DbSet<meetings> meetings { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<room_times> room_times { get; set; }
        public virtual DbSet<rooms> rooms { get; set; }
        public virtual DbSet<therapist_treatments> therapist_treatments { get; set; }
        public virtual DbSet<therapists> therapists { get; set; }
        public virtual DbSet<times> times { get; set; }
        public virtual DbSet<Tlocations> Tlocations { get; set; }
        public virtual DbSet<treatments> treatments { get; set; }
    }
}
